//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeSome.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;
    using System.IO;

    public partial class espisode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public espisode()
        {
            this.favorites = new HashSet<favorite>();
        }
        [DisplayName("ID")]
        public int vidID { get; set; }
        [DisplayName("Nhập đường dẫn video")]
        public string vidAddress { get; set; }
        [DisplayName("Thêm ảnh")]
        public string vidIMG { get; set; }
        [DisplayName("Tập phim của phim")]
        public Nullable<int> film_ID { get; set; }
        public Nullable<int> Espisode1 { get; set; }
    
        public virtual Film Film { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<favorite> favorites { get; set; }
        [NotMapped]
        public HttpPostedFileBase IMGupload { get; set; }
    }
}
