//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeSome.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;
    using System.IO;

    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.espisodes = new HashSet<espisode>();
        }
        [DisplayName("ID")]
        public int filmID { get; set; }
        [DisplayName("Tên")]
        [Required(ErrorMessage = "Tên phim không được trống")]
        public string filmTitle { get; set; }
        [DisplayName("Mô tả")]
        [Required(ErrorMessage = "Bạn chưa viết mô tả")]
        public string filmDes { get; set; }
        [DisplayName("Số tập")]
        public int filmEsp { get; set; }
        [DisplayName("Trạng thái")]
        [Required(ErrorMessage = "Bạn chưa chọn trạng thái")]
        public string filmStatus { get; set; }
        [DisplayName("Đường dẫn phim")]
        [Required(ErrorMessage = "Bạn chưa tải lên phim")]
        public string filmLink { get; set; }
        [DisplayName("Thumbnail")]
        [Required(ErrorMessage = "Bạn chưa tải lên hình")]
        public string filmIMG { get; set; }

        [DisplayName("Thể loại")]
        [Required(ErrorMessage = "Bạn chưa chọn thể loại")]
        public Nullable<int> filmGenre { get; set; }
        public Nullable<int> SumEspisode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<espisode> espisodes { get; set; }
        public virtual genre genre { get; set; }
        [NotMapped]
        public HttpPostedFileBase IMGupload { get; set; }
    }
}
