//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeSome.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;
    using System.IO;
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.espisodes = new HashSet<espisode>();
        }
    
        public int filmID { get; set; }
        public string filmTitle { get; set; }
        public string filmDes { get; set; }
        public int filmEsp { get; set; }
        public string filmStatus { get; set; }
        public string filmLink { get; set; }
        public string filmIMG { get; set; }
        public Nullable<int> filmGenre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<espisode> espisodes { get; set; }
        public virtual genre genre { get; set; }
        [NotMapped]
        public HttpPostedFileBase IMGupload { get; set; }
    }
}
