//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeSome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class genre
    {
        public int genreID { get; set; }
        public string genreName { get; set; }
        public Nullable<int> film_ID { get; set; }
    
        public virtual Film Film { get; set; }
    }
}
