//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeSome.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class UserTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserTable()
        {
            this.favorites = new HashSet<favorite>();
        }
    
        public int userID { get; set; }
        public string userName { get; set; }
        
        public string userPass { get; set; }
       
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<System.DateTime> userDate { get; set; }
        public string userEmail { get; set; }
        public int userPhone { get; set; }
        public string Sex { get; set; }
        public string MoneyCheck { get; set; }
        public Nullable<int> FavoriteVideo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<favorite> favorites { get; set; } 
        [NotMapped]
        [Compare("userPass")]
        [Required(ErrorMessage = "Not empty")]
        public string userRepass { get; set; }
    }
}
