//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeSome.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;
    using System.IO;

    public partial class UserTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserTable()
        {
            this.favorites = new HashSet<favorite>();
        }
        [DisplayName("ID")]
        public int userID { get; set; }
        [DisplayName("Tên đăng nhập")]
        [Required(ErrorMessage = "Bạn chưa nhập tên đăng nhập")]
        public string userName { get; set; }
        [DisplayName("Mật khẩu")]
        [Required(ErrorMessage = "Bạn chưa nhập mật khẩu")]
        public string userPass { get; set; }
        [DisplayName("Họ")]
        [Required(ErrorMessage = "Bạn chưa nhập họ")]
        public string firstName { get; set; }
        [DisplayName("Tên")]
        [Required(ErrorMessage = "Bạn chưa nhập tên")]
        public string lastName { get; set; }
        public Nullable<System.DateTime> userDate { get; set; }
        [DisplayName("Email")]
        [Required(ErrorMessage = "Bạn chưa nhập email")]
        public string userEmail { get; set; }
        [DisplayName("SĐT")]
        [Required(ErrorMessage = "Bạn chưa nhập SDT")]
        public int userPhone { get; set; }
        public string Sex { get; set; }
        public Nullable<int> FavoriteVideo { get; set; }
        public Nullable<bool> userRole { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<favorite> favorites { get; set; }
        [NotMapped]
        [Compare("userPass")]
        [Required(ErrorMessage = "Not empty")]
        public string userRepass { get; set; }
    }
}
