//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeSome.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WEBEntitiesEntities : DbContext
    {
        public WEBEntitiesEntities()
            : base("name=WEBEntitiesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminTable> AdminTables { get; set; }
        public virtual DbSet<espisode> espisodes { get; set; }
        public virtual DbSet<favorite> favorites { get; set; }
        public virtual DbSet<Film> Films { get; set; }
        public virtual DbSet<genre> genres { get; set; }
        public virtual DbSet<UserTable> UserTables { get; set; }
    }
}
